In [18]:
import pandas as pd

In [19]:
data_cause = pd.read_csv("cause_of_deaths.csv", sep=",")

In [20]:
data_w_pop = pd.read_csv("World-population-by-countries-dataset.csv", sep=",")

In [21]:
data_cause.head(3)

,Country/Territory,Code,Year,Meningitis,Alzheimer's Disease and Other Dementias,Parkinson's Disease,Nutritional Deficiencies,Malaria,Drowning,Interpersonal Violence,...,Diabetes Mellitus,Chronic Kidney Disease,Poisonings,Protein-Energy Malnutrition,Road Injuries,Chronic Respiratory Diseases,Cirrhosis and Other Chronic Liver Diseases,Digestive Diseases,"Fire, Heat, and Hot Substances",Acute Hepatitis
0,Afghanistan,AFG,1990,2159,1116,371,2087,93,1370,1538,...,2108,3709,338,2054,4154,5945,2673,5005,323,2985
1,Afghanistan,AFG,1991,2218,1136,374,2153,189,1391,2001,...,2120,3724,351,2119,4472,6050,2728,5120,332,3092
2,Afghanistan,AFG,1992,2475,1162,378,2441,239,1514,2299,...,2153,3776,386,2404,5106,6223,2830,5335,360,3325

In [22]:
data_w_pop.head(3)

,Country Name,Country Code,1960,1961,1962,1963,1964,1965,1966,1967,...,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021
0,Aruba,ABW,54208.0,55434.0,56234.0,56699.0,57029.0,57357.0,57702.0,58044.0,...,102565.0,103165.0,103776.0,104339.0,104865.0,105361.0,105846.0,106310.0,106766.0,107195.0
1,Africa Eastern and Southern,AFE,130836765.0,134159786.0,137614644.0,141202036.0,144920186.0,148769974.0,152752671.0,156876454.0,...,547482863.0,562601578.0,578075373.0,593871847.0,609978946.0,626392880.0,643090131.0,660046272.0,677243299.0,694665117.0
2,Afghanistan,AFG,8996967.0,9169406.0,9351442.0,9543200.0,9744772.0,9956318.0,10174840.0,10399936.0,...,31161378.0,32269592.0,33370804.0,34413603.0,35383028.0,36296111.0,37171922.0,38041757.0,38928341.0,39835428.0

In [23]:
dataset_final = data_cause.copy()

In [24]:
dataset_final["Population"] = 0

In [25]:
dataset_final.head(3)

,Country/Territory,Code,Year,Meningitis,Alzheimer's Disease and Other Dementias,Parkinson's Disease,Nutritional Deficiencies,Malaria,Drowning,Interpersonal Violence,...,Chronic Kidney Disease,Poisonings,Protein-Energy Malnutrition,Road Injuries,Chronic Respiratory Diseases,Cirrhosis and Other Chronic Liver Diseases,Digestive Diseases,"Fire, Heat, and Hot Substances",Acute Hepatitis,Population
0,Afghanistan,AFG,1990,2159,1116,371,2087,93,1370,1538,...,3709,338,2054,4154,5945,2673,5005,323,2985,0
1,Afghanistan,AFG,1991,2218,1136,374,2153,189,1391,2001,...,3724,351,2119,4472,6050,2728,5120,332,3092,0
2,Afghanistan,AFG,1992,2475,1162,378,2441,239,1514,2299,...,3776,386,2404,5106,6223,2830,5335,360,3325,0

In [26]:
dataset_final.columns

Index(['Country/Territory', 'Code', 'Year', 'Meningitis',
       'Alzheimer's Disease and Other Dementias', 'Parkinson's Disease',
       'Nutritional Deficiencies', 'Malaria', 'Drowning',
       'Interpersonal Violence', 'Maternal Disorders', 'HIV/AIDS',
       'Drug Use Disorders', 'Tuberculosis', 'Cardiovascular Diseases',
       'Lower Respiratory Infections', 'Neonatal Disorders',
       'Alcohol Use Disorders', 'Self-harm', 'Exposure to Forces of Nature',
       'Diarrheal Diseases', 'Environmental Heat and Cold Exposure',
       'Neoplasms', 'Conflict and Terrorism', 'Diabetes Mellitus',
       'Chronic Kidney Disease', 'Poisonings', 'Protein-Energy Malnutrition',
       'Road Injuries', 'Chronic Respiratory Diseases',
       'Cirrhosis and Other Chronic Liver Diseases', 'Digestive Diseases',
       'Fire, Heat, and Hot Substances', 'Acute Hepatitis', 'Population'],
      dtype='object')

In [27]:
dataset_final = dataset_final[['Country/Territory', 'Code', 'Year', 'Population', 'Meningitis',
       "Alzheimer's Disease and Other Dementias", "Parkinson's Disease",
       'Nutritional Deficiencies', 'Malaria', 'Drowning',
       'Interpersonal Violence', 'Maternal Disorders', 'HIV/AIDS',
       'Drug Use Disorders', 'Tuberculosis', 'Cardiovascular Diseases',
       'Lower Respiratory Infections', 'Neonatal Disorders',
       'Alcohol Use Disorders', 'Self-harm', 'Exposure to Forces of Nature',
       'Diarrheal Diseases', 'Environmental Heat and Cold Exposure',
       'Neoplasms', 'Conflict and Terrorism', 'Diabetes Mellitus',
       'Chronic Kidney Disease', 'Poisonings', 'Protein-Energy Malnutrition',
       'Road Injuries', 'Chronic Respiratory Diseases',
       'Cirrhosis and Other Chronic Liver Diseases', 'Digestive Diseases',
       'Fire, Heat, and Hot Substances', 'Acute Hepatitis']]

In [28]:
dataset_final.head(3)

,Country/Territory,Code,Year,Population,Meningitis,Alzheimer's Disease and Other Dementias,Parkinson's Disease,Nutritional Deficiencies,Malaria,Drowning,...,Diabetes Mellitus,Chronic Kidney Disease,Poisonings,Protein-Energy Malnutrition,Road Injuries,Chronic Respiratory Diseases,Cirrhosis and Other Chronic Liver Diseases,Digestive Diseases,"Fire, Heat, and Hot Substances",Acute Hepatitis
0,Afghanistan,AFG,1990,0,2159,1116,371,2087,93,1370,...,2108,3709,338,2054,4154,5945,2673,5005,323,2985
1,Afghanistan,AFG,1991,0,2218,1136,374,2153,189,1391,...,2120,3724,351,2119,4472,6050,2728,5120,332,3092
2,Afghanistan,AFG,1992,0,2475,1162,378,2441,239,1514,...,2153,3776,386,2404,5106,6223,2830,5335,360,3325

In [29]:
for idx in data_cause.index:
    year = data_cause.iloc[idx, 2]
    code = data_cause.iloc[idx, 1]
    tmp = data_w_pop[[str(year), "Country Code"]][data_w_pop["Country Code"] == code]
    tmp = tmp.reset_index(drop=True)
    if tmp.shape[0] == 0:
        print(idx, " => code = ", code, " , year = ", year, " shape tmp = ", tmp.shape)
    else:
        dataset_final.iloc[idx, 3] = tmp.iloc[0,0]

1230  => code =  COK  , year =  1990  shape tmp =  (0, 2)
1231  => code =  COK  , year =  1991  shape tmp =  (0, 2)
1232  => code =  COK  , year =  1992  shape tmp =  (0, 2)
1233  => code =  COK  , year =  1993  shape tmp =  (0, 2)
1234  => code =  COK  , year =  1994  shape tmp =  (0, 2)
1235  => code =  COK  , year =  1995  shape tmp =  (0, 2)
1236  => code =  COK  , year =  1996  shape tmp =  (0, 2)
1237  => code =  COK  , year =  1997  shape tmp =  (0, 2)
1238  => code =  COK  , year =  1998  shape tmp =  (0, 2)
1239  => code =  COK  , year =  1999  shape tmp =  (0, 2)
1240  => code =  COK  , year =  2000  shape tmp =  (0, 2)
1241  => code =  COK  , year =  2001  shape tmp =  (0, 2)
1242  => code =  COK  , year =  2002  shape tmp =  (0, 2)
1243  => code =  COK  , year =  2003  shape tmp =  (0, 2)
1244  => code =  COK  , year =  2004  shape tmp =  (0, 2)
1245  => code =  COK  , year =  2005  shape tmp =  (0, 2)
1246  => code =  COK  , year =  2006  shape tmp =  (0, 2)
1247  => code =  COK  , year =  2007  shape tmp =  (0, 2)
1248  => code =  COK  , year =  2008  shape tmp =  (0, 2)
1249  => code =  COK  , year =  2009  shape tmp =  (0, 2)
1250  => code =  COK  , year =  2010  shape tmp =  (0, 2)
1251  => code =  COK  , year =  2011  shape tmp =  (0, 2)
1252  => code =  COK  , year =  2012  shape tmp =  (0, 2)
1253  => code =  COK  , year =  2013  shape tmp =  (0, 2)
1254  => code =  COK  , year =  2014  shape tmp =  (0, 2)
1255  => code =  COK  , year =  2015  shape tmp =  (0, 2)
1256  => code =  COK  , year =  2016  shape tmp =  (0, 2)
1257  => code =  COK  , year =  2017  shape tmp =  (0, 2)
1258  => code =  COK  , year =  2018  shape tmp =  (0, 2)
1259  => code =  COK  , year =  2019  shape tmp =  (0, 2)
3900  => code =  NIU  , year =  1990  shape tmp =  (0, 2)
3901  => code =  NIU  , year =  1991  shape tmp =  (0, 2)
3902  => code =  NIU  , year =  1992  shape tmp =  (0, 2)
3903  => code =  NIU  , year =  1993  shape tmp =  (0, 2)
3904  => code =  NIU  , year =  1994  shape tmp =  (0, 2)
3905  => code =  NIU  , year =  1995  shape tmp =  (0, 2)
3906  => code =  NIU  , year =  1996  shape tmp =  (0, 2)
3907  => code =  NIU  , year =  1997  shape tmp =  (0, 2)
3908  => code =  NIU  , year =  1998  shape tmp =  (0, 2)
3909  => code =  NIU  , year =  1999  shape tmp =  (0, 2)
3910  => code =  NIU  , year =  2000  shape tmp =  (0, 2)
3911  => code =  NIU  , year =  2001  shape tmp =  (0, 2)
3912  => code =  NIU  , year =  2002  shape tmp =  (0, 2)
3913  => code =  NIU  , year =  2003  shape tmp =  (0, 2)
3914  => code =  NIU  , year =  2004  shape tmp =  (0, 2)
3915  => code =  NIU  , year =  2005  shape tmp =  (0, 2)
3916  => code =  NIU  , year =  2006  shape tmp =  (0, 2)
3917  => code =  NIU  , year =  2007  shape tmp =  (0, 2)
3918  => code =  NIU  , year =  2008  shape tmp =  (0, 2)
3919  => code =  NIU  , year =  2009  shape tmp =  (0, 2)
3920  => code =  NIU  , year =  2010  shape tmp =  (0, 2)
3921  => code =  NIU  , year =  2011  shape tmp =  (0, 2)
3922  => code =  NIU  , year =  2012  shape tmp =  (0, 2)
3923  => code =  NIU  , year =  2013  shape tmp =  (0, 2)
3924  => code =  NIU  , year =  2014  shape tmp =  (0, 2)
3925  => code =  NIU  , year =  2015  shape tmp =  (0, 2)
3926  => code =  NIU  , year =  2016  shape tmp =  (0, 2)
3927  => code =  NIU  , year =  2017  shape tmp =  (0, 2)
3928  => code =  NIU  , year =  2018  shape tmp =  (0, 2)
3929  => code =  NIU  , year =  2019  shape tmp =  (0, 2)
5310  => code =  TWN  , year =  2007  shape tmp =  (0, 2)
5311  => code =  TWN  , year =  2008  shape tmp =  (0, 2)
5312  => code =  TWN  , year =  2009  shape tmp =  (0, 2)
5313  => code =  TWN  , year =  2010  shape tmp =  (0, 2)
5314  => code =  TWN  , year =  2011  shape tmp =  (0, 2)
5315  => code =  TWN  , year =  2012  shape tmp =  (0, 2)
5316  => code =  TWN  , year =  2013  shape tmp =  (0, 2)
5317  => code =  TWN  , year =  2014  shape tmp =  (0, 2)
5318  => code =  TWN  , year =  2015  shape tmp =  (0, 2)
5319  => code =  TWN  , year =  2016  shape tmp =  (0, 2)
5320  => code =  TWN  , year =  1990  shape tmp =  (0, 2)
5321  => code =  TWN  , year =  1991  shape tmp =  (0, 2)
5322  => code =  TWN  , year =  1992  shape tmp =  (0, 2)
5323  => code =  TWN  , year =  1993  shape tmp =  (0, 2)
5324  => code =  TWN  , year =  1994  shape tmp =  (0, 2)
5325  => code =  TWN  , year =  1995  shape tmp =  (0, 2)
5326  => code =  TWN  , year =  1996  shape tmp =  (0, 2)
5327  => code =  TWN  , year =  1997  shape tmp =  (0, 2)
5328  => code =  TWN  , year =  1998  shape tmp =  (0, 2)
5329  => code =  TWN  , year =  1999  shape tmp =  (0, 2)
5330  => code =  TWN  , year =  2000  shape tmp =  (0, 2)
5331  => code =  TWN  , year =  2001  shape tmp =  (0, 2)
5332  => code =  TWN  , year =  2002  shape tmp =  (0, 2)
5333  => code =  TWN  , year =  2003  shape tmp =  (0, 2)
5334  => code =  TWN  , year =  2004  shape tmp =  (0, 2)
5335  => code =  TWN  , year =  2005  shape tmp =  (0, 2)
5336  => code =  TWN  , year =  2006  shape tmp =  (0, 2)
5337  => code =  TWN  , year =  2017  shape tmp =  (0, 2)
5338  => code =  TWN  , year =  2018  shape tmp =  (0, 2)
5339  => code =  TWN  , year =  2019  shape tmp =  (0, 2)
5490  => code =  TKL  , year =  1990  shape tmp =  (0, 2)
5491  => code =  TKL  , year =  1991  shape tmp =  (0, 2)
5492  => code =  TKL  , year =  1992  shape tmp =  (0, 2)
5493  => code =  TKL  , year =  1993  shape tmp =  (0, 2)
5494  => code =  TKL  , year =  1994  shape tmp =  (0, 2)
5495  => code =  TKL  , year =  1995  shape tmp =  (0, 2)
5496  => code =  TKL  , year =  1996  shape tmp =  (0, 2)
5497  => code =  TKL  , year =  1997  shape tmp =  (0, 2)
5498  => code =  TKL  , year =  1998  shape tmp =  (0, 2)
5499  => code =  TKL  , year =  1999  shape tmp =  (0, 2)
5500  => code =  TKL  , year =  2000  shape tmp =  (0, 2)
5501  => code =  TKL  , year =  2001  shape tmp =  (0, 2)
5502  => code =  TKL  , year =  2002  shape tmp =  (0, 2)
5503  => code =  TKL  , year =  2003  shape tmp =  (0, 2)
5504  => code =  TKL  , year =  2004  shape tmp =  (0, 2)
5505  => code =  TKL  , year =  2005  shape tmp =  (0, 2)
5506  => code =  TKL  , year =  2006  shape tmp =  (0, 2)
5507  => code =  TKL  , year =  2007  shape tmp =  (0, 2)
5508  => code =  TKL  , year =  2008  shape tmp =  (0, 2)
5509  => code =  TKL  , year =  2009  shape tmp =  (0, 2)
5510  => code =  TKL  , year =  2010  shape tmp =  (0, 2)
5511  => code =  TKL  , year =  2011  shape tmp =  (0, 2)
5512  => code =  TKL  , year =  2012  shape tmp =  (0, 2)
5513  => code =  TKL  , year =  2013  shape tmp =  (0, 2)
5514  => code =  TKL  , year =  2014  shape tmp =  (0, 2)
5515  => code =  TKL  , year =  2015  shape tmp =  (0, 2)
5516  => code =  TKL  , year =  2016  shape tmp =  (0, 2)
5517  => code =  TKL  , year =  2017  shape tmp =  (0, 2)
5518  => code =  TKL  , year =  2018  shape tmp =  (0, 2)
5519  => code =  TKL  , year =  2019  shape tmp =  (0, 2)

In [30]:
dataset_final.drop(dataset_final[dataset_final["Population"] == 0].index, inplace=True)

In [31]:
dataset_final.to_csv("cause_of_deaths_with_population.csv", sep=",", index=False)

In [32]:
dataset_final

,Country/Territory,Code,Year,Population,Meningitis,Alzheimer's Disease and Other Dementias,Parkinson's Disease,Nutritional Deficiencies,Malaria,Drowning,...,Diabetes Mellitus,Chronic Kidney Disease,Poisonings,Protein-Energy Malnutrition,Road Injuries,Chronic Respiratory Diseases,Cirrhosis and Other Chronic Liver Diseases,Digestive Diseases,"Fire, Heat, and Hot Substances",Acute Hepatitis
0,Afghanistan,AFG,1990,12412311.0,2159,1116,371,2087,93,1370,...,2108,3709,338,2054,4154,5945,2673,5005,323,2985
1,Afghanistan,AFG,1991,13299016.0,2218,1136,374,2153,189,1391,...,2120,3724,351,2119,4472,6050,2728,5120,332,3092
2,Afghanistan,AFG,1992,14485543.0,2475,1162,378,2441,239,1514,...,2153,3776,386,2404,5106,6223,2830,5335,360,3325
3,Afghanistan,AFG,1993,15816601.0,2812,1187,384,2837,108,1687,...,2195,3862,425,2797,5681,6445,2943,5568,396,3601
4,Afghanistan,AFG,1994,17075728.0,3027,1211,391,3081,211,1809,...,2231,3932,451,3038,6001,6664,3027,5739,420,3816
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6115,Zimbabwe,ZWE,2015,13814642.0,1439,754,215,3019,2518,770,...,3176,2108,381,2990,2373,2751,1956,4202,632,146
6116,Zimbabwe,ZWE,2016,14030338.0,1457,767,219,3056,2050,801,...,3259,2160,393,3027,2436,2788,1962,4264,648,146
6117,Zimbabwe,ZWE,2017,14236599.0,1460,781,223,2990,2116,818,...,3313,2196,398,2962,2473,2818,2007,4342,654,144
6118,Zimbabwe,ZWE,2018,14438812.0,1450,795,227,2918,2088,825,...,3381,2240,400,2890,2509,2849,2030,4377,657,139
6119,Zimbabwe,ZWE,2019,14645473.0,1450,812,232,2884,2068,827,...,3460,2292,405,2855,2554,2891,2065,4437,662,136